import React, { useState, useEffect } from 'react';
import { 
  Calendar, 
  ChevronDown, 
  ChevronUp,
  RefreshCw,
  Leaf,
  Filter,
  X,
  Package,
  Activity,
  Info,
  FileDown,
  Languages 
} from 'lucide-react';
import toast, { Toaster } from 'react-hot-toast';
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

// Utility to chunk arrays into smaller arrays for multiple rows
const chunkArray = (arr, size) => {
  const chunked = [];
  for (let i = 0; i < arr.length; i += size) {
    chunked.push(arr.slice(i, i + size));
  }
  return chunked;
};

// Helper to get local date in YYYY-MM-DD format for default filter
const getTodayDate = () => {
  const today = new Date();
  const yyyy = today.getFullYear();
  const mm = String(today.getMonth() + 1).padStart(2, '0');
  const dd = String(today.getDate()).padStart(2, '0');
  return `${yyyy}-${mm}-${dd}`;
};

const WitherLeafSummary = () => {
  const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'http://localhost:5000';
  
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [expandedGroups, setExpandedGroups] = useState({});
  const [filterDate, setFilterDate] = useState(getTodayDate());
  const [generatingPdf, setGeneratingPdf] = useState(false);

  // User details from localStorage for the PDF footer
  const userRole = localStorage.getItem("userRole") || "Admin";
  const currentUsername = localStorage.getItem("username") || "admin";

  // 💡 Language Toggle State ("EN" or "SI")
  const [lang, setLang] = useState("EN");

  // 💡 --- DYNAMIC TRANSLATIONS ---
  const t = {
    title: lang === 'SI' ? "මැලවූ දළු සාරාංශ වාර්තාව" : "Wither Leaf Summary Report",
    subtitle: lang === 'SI' ? "දෛනික මැලවූ දළු සහ කාණ්ඩ විස්තර වාර්තාව." : "Daily consolidated report of all wither leaf and batch data.",
    sync: lang === 'SI' ? "යාවත්කාලීන කරන්න" : "Sync",
    refreshing: lang === 'SI' ? "යාවත්කාලීන වෙමින්..." : "Refreshing...",
    downloadPdf: lang === 'SI' ? "PDF බාගත කරන්න" : "Download PDF",
    
    filterDay: lang === 'SI' ? "දිනය අනුව පෙරහන් කරන්න:" : "Filter by Day:",
    cropDate: lang === 'SI' ? "අස්වැන්න දිනය" : "Crop Date",
    clear: lang === 'SI' ? "මකන්න" : "Clear",
    
    loading: lang === 'SI' ? "වාර්තා පූරණය වෙමින් පවතී..." : "Loading reports...",
    noRecords: lang === 'SI' ? "වාර්තා කිසිවක් හමු නොවීය" : "No Records Found",
    noRecordsDesc: lang === 'SI' ? "තෝරාගත් දිනය සඳහා මැලවූ දළු දත්ත කිසිවක් නොමැත." : "There is no wither leaf data available for the selected date.",
    
    mfDate: lang === 'SI' ? "නිෂ්පාදිත දිනය" : "M/F Date",
    totalCrop: lang === 'SI' ? "මුළු දළු" : "Total Crop",
    
    batchQty: lang === 'SI' ? "කාණ්ඩ ප්‍රමාණ" : "Batch Quantities",
    batchNo: lang === 'SI' ? "කාණ්ඩ අංකය" : "Batch No",
    kg: lang === 'SI' ? "Kg" : "Kg",
    noBatches: lang === 'SI' ? "මෙම දිනය සඳහා කාණ්ඩ කිසිවක් වාර්තා කර නොමැත." : "No batches recorded for this day.",
    
    prodSummary: lang === 'SI' ? "නිෂ්පාදන සාරාංශය" : "Production Summary",
    greenLeaf: lang === 'SI' ? "අමු දළු" : "Green Leaf",
    witherLeaf: lang === 'SI' ? "මැලවූ දළු" : "Wither Leaf",
    witheringP: lang === 'SI' ? "මැලවීමේ ප්‍රතිශතය" : "Withering (P)",
    quality: lang === 'SI' ? "ගුණාත්මය" : "Quality",
    factory: lang === 'SI' ? "කර්මාන්තශාලාව" : "Factory",
    opsPeriod: lang === 'SI' ? "මෙහෙයුම් කාලය" : "Ops Period",
    
    genBy: lang === 'SI' ? "සකස් කළේ:" : "Generated By:",
    authSig: lang === 'SI' ? "පරීක්ෂා කළේ / අත්සන" : "Checked By / Signature",
    docRef: lang === 'SI' ? "ලේඛන අංකය" : "Doc Ref",
    generated: lang === 'SI' ? "ජනනය කරන ලදී" : "Generated"
  };

  const fetchRecords = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem("token");
      const response = await fetch(`${BACKEND_URL}/api/wither-leaf`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });

      const result = await response.json();
      if (response.ok && result.success) {
        setRecords(result.data);
      } else {
        toast.error("Failed to load records.");
      }
    } catch (error) {
      console.error("Error fetching data:", error);
      toast.error("Connection error while fetching records.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecords();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const toggleGroup = (groupKey) => {
    setExpandedGroups(prev => ({ ...prev, [groupKey]: !prev[groupKey] }));
  };

  const clearFilter = () => setFilterDate("");

  const filteredRecords = records.filter(record => {
    if (!filterDate) return true;
    const recordDate = record.dateOfCrop || (record.createdAt ? record.createdAt.split('T')[0] : '');
    return recordDate === filterDate;
  });

  const groupedRecords = filteredRecords.reduce((acc, record) => {
    const cropDate = record.dateOfCrop || 'Unknown Crop Date';
    const mfDate = record.dateOfManufacture || 'Unknown M/F Date';
    
    const groupKey = `${cropDate}|${mfDate}`;
    if (!acc[groupKey]) acc[groupKey] = [];
    acc[groupKey].push(record);
    return acc;
  }, {});

  const sortedGroupKeys = Object.keys(groupedRecords).sort((a, b) => {
    if (a.startsWith('Unknown')) return 1;
    if (b.startsWith('Unknown')) return -1;
    const dateA = a.split('|')[0];
    const dateB = b.split('|')[0];
    return new Date(dateB) - new Date(dateA);
  });

  // =========================================================
  // --- DIRECT DOWNLOAD PDF (Beautified High-Quality Export) ---
  // =========================================================
  const handleDownloadPDF = async (groupKey) => {
    const printElement = document.getElementById(`pdf-print-area-${groupKey}`);
    if (!printElement) return;

    setGeneratingPdf(true);
    const toastId = toast.loading("Generating PDF Report...");

    try {
      printElement.style.display = "block";
      printElement.style.position = "absolute";
      printElement.style.top = "-9999px";

      const canvas = await html2canvas(printElement, {
        scale: 2.5,
        useCORS: true,
        backgroundColor: "#ffffff",
        logging: false,
        onclone: (clonedDoc) => {
          const stylesheets = clonedDoc.querySelectorAll('link[rel="stylesheet"], style');
          stylesheets.forEach(sheet => sheet.remove());
        }
      });

      printElement.style.display = "none";

      const imgData = canvas.toDataURL('image/jpeg', 0.90);

      const pdf = new jsPDF('landscape', 'pt', 'a4');
      const pdfPageWidth = pdf.internal.pageSize.getWidth();
      const pdfPageHeight = pdf.internal.pageSize.getHeight();

      const margin = 20;
      const maxW = pdfPageWidth - (margin * 2);
      const maxH = pdfPageHeight - (margin * 2);

      let finalW = maxW;
      let finalH = (canvas.height * finalW) / canvas.width;

      if (finalH > maxH) {
        finalH = maxH;
        finalW = (canvas.width * finalH) / canvas.height;
      }

      const x = (pdfPageWidth - finalW) / 2;
      const y = margin;

      pdf.addImage(imgData, 'JPEG', x, y, finalW, finalH);
      pdf.save(`Wither_Leaf_Summary_${filterDate || 'Report'}.pdf`);

      toast.success("PDF downloaded successfully!", { id: toastId });
    } catch (error) {
      console.error("PDF Generation Error:", error);
      toast.error("Failed to generate PDF.", { id: toastId });
    } finally {
      setGeneratingPdf(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#f8f9fa] p-4 md:p-8 font-sans">
      <Toaster position="bottom-right" />
      
      {/* Page Header */}
      <div className="max-w-6xl mx-auto mb-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <Leaf className="w-7 h-7 text-green-700" />
            <h1 className="text-2xl font-bold text-green-800 tracking-tight">{t.title}</h1>
          </div>
          <p className="text-sm text-gray-500 mt-1 ml-9">{t.subtitle}</p>
        </div>
        
        <div className="flex flex-row flex-wrap sm:flex-nowrap items-center gap-2 sm:gap-3 w-full md:w-auto">
          {/* 💡 LANGUAGE TOGGLE BUTTON */}
          <button
            onClick={() => setLang(lang === 'EN' ? 'SI' : 'EN')}
            className="p-2.5 px-4 bg-indigo-50 text-indigo-700 hover:bg-indigo-100 border border-indigo-200 rounded-lg transition-colors shadow-sm font-bold text-sm flex items-center gap-2"
            title="Toggle Language"
          >
            <Languages size={18} />
            {lang === 'EN' ? "සිංහල" : "English"}
          </button>

          <button 
            onClick={fetchRecords} 
            disabled={loading}
            className="flex-1 sm:flex-none justify-center bg-white border border-gray-200 hover:bg-gray-50 text-gray-700 font-semibold py-2 sm:py-2.5 px-4 rounded-lg shadow-sm flex items-center gap-2 transition-colors text-sm"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            {loading ? t.refreshing : t.sync}
          </button>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="max-w-6xl mx-auto mb-8 bg-white p-4 rounded-xl border border-gray-200 shadow-sm flex flex-col sm:flex-row items-start sm:items-center gap-4 sm:gap-6">
        <div className="flex items-center gap-2 text-gray-700 font-semibold text-sm">
          <Filter className="w-4 h-4 text-green-600" />
          {t.filterDay}
        </div>
        <div className="flex flex-wrap items-center gap-4">
          <div className="flex items-center gap-2">
            <label className="text-[10px] font-bold text-gray-500 uppercase">{t.cropDate}</label>
            <input 
              type="date" 
              value={filterDate}
              onChange={(e) => setFilterDate(e.target.value)}
              className="bg-gray-50 border border-gray-200 text-gray-800 text-sm rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500 outline-none p-2"
            />
          </div>
          {filterDate && (
            <button 
              onClick={clearFilter}
              className="flex items-center gap-1 text-xs font-bold text-red-500 hover:text-red-700 bg-red-50 hover:bg-red-100 px-3 py-2 rounded-lg transition-colors"
            >
              <X className="w-3.5 h-3.5" /> {t.clear}
            </button>
          )}
        </div>
      </div>

      {/* UI Content Generation */}
      <div className="max-w-6xl mx-auto flex flex-col gap-6">
        {loading && records.length === 0 ? (
          <div className="text-center py-20 bg-white rounded-2xl border border-gray-200 shadow-sm">
            <div className="w-10 h-10 border-4 border-green-200 border-t-green-600 rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-gray-500 font-medium">{t.loading}</p>
          </div>
        ) : sortedGroupKeys.length === 0 ? (
          <div className="text-center py-20 bg-white rounded-2xl border border-gray-200 shadow-sm">
            <Package className="w-12 h-12 text-gray-300 mx-auto mb-3" />
            <h3 className="text-lg font-bold text-gray-700">{t.noRecords}</h3>
            <p className="text-gray-500 text-sm">{t.noRecordsDesc}</p>
          </div>
        ) : (
          sortedGroupKeys.map((groupKey) => {
            const dayRecords = groupedRecords[groupKey];
            const isExpanded = expandedGroups[groupKey] !== false; 
            
            const [cropDateStr, mfDateStr] = groupKey.split('|');

            const formatDate = (dStr) => {
              if (dStr.startsWith('Unknown')) return dStr;
              const d = new Date(dStr);
              return d.toLocaleDateString('en-GB'); 
            };

            const formattedCropDate = formatDate(cropDateStr);
            const formattedMFDate = formatDate(mfDateStr);
            
            const consolidated = dayRecords.reduce((acc, curr) => {
              if (curr.factory) acc.factory = curr.factory;
              if (curr.receivedTotalCropKg) acc.receivedTotalCropKg = curr.receivedTotalCropKg;
              if (curr.witheredLeafKg) acc.witheredLeafKg = curr.witheredLeafKg;
              if (curr.percentage) acc.percentage = curr.percentage;
              if (curr.weatheringQuality) acc.weatheringQuality = curr.weatheringQuality;
              if (curr.startTime) acc.startTime = curr.startTime;
              if (curr.finishTime) acc.finishTime = curr.finishTime;
              if (curr.period) acc.period = curr.period;
              if (curr.totalEmployee) acc.totalEmployee = curr.totalEmployee;
              if (curr.noOfBatchers) acc.noOfBatchers = curr.noOfBatchers;

              if (curr.batches) {
                curr.batches.forEach((val, i) => {
                  if (val > 0) acc.batches[i] += val; 
                });
              }
              return acc;
            }, { batches: Array(25).fill(0) });

            const activeBatches = consolidated.batches.map((kg, i) => ({ num: String(i + 1).padStart(2, '0'), kg })).filter(b => b.kg > 0);
            const hasBatches = activeBatches.length > 0;
            const totalReceived = consolidated.receivedTotalCropKg || 0;

            const docRefCode = `WL/SUM/${new Date().toLocaleString("default", { month: "long" }).toUpperCase()}.${new Date().getFullYear()}`;
            const currentTimestamp = `${new Date().getFullYear()}/${String(new Date().getMonth() + 1).padStart(2, '0')}/${String(new Date().getDate()).padStart(2, '0')} ${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }).toLowerCase()}`;
            
            return (
              <div 
                key={groupKey} 
                className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden transition-all duration-300"
              >
                
                {/* Header Container */}
                <div 
                  onClick={() => toggleGroup(groupKey)}
                  className="bg-white hover:bg-green-50/30 p-5 cursor-pointer flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 transition-colors"
                >
                  <div className="flex items-center gap-4">
                    <div className="p-2.5 bg-green-100/50 text-green-600 rounded-lg">
                      <Calendar className="w-5 h-5" />
                    </div>
                    <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-6">
                      <div className="flex flex-col">
                         <span className="text-[10px] text-gray-500 font-bold uppercase tracking-wider">{t.cropDate}</span>
                         <span className="text-lg font-black text-gray-800">{formattedCropDate}</span>
                      </div>
                      <span className="hidden sm:block text-gray-300">|</span>
                      <div className="flex flex-col">
                         <span className="text-[10px] text-gray-500 font-bold uppercase tracking-wider">{t.mfDate}</span>
                         <span className="text-lg font-black text-gray-800">{formattedMFDate}</span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-4 w-full sm:w-auto mt-3 sm:mt-0">
                    {totalReceived > 0 && (
                      <div className="hidden sm:block text-right mr-2">
                        <p className="text-[10px] uppercase font-bold text-gray-400">{t.totalCrop}</p>
                        <p className="text-sm font-bold text-gray-800">{Number(totalReceived).toFixed(2)} kg</p>
                      </div>
                    )}
                    
                    {/* --- PDF DOWNLOAD BUTTON --- */}
                    {isExpanded && (
                      <button 
                        onClick={(e) => {
                          e.stopPropagation(); 
                          handleDownloadPDF(groupKey);
                        }}
                        disabled={generatingPdf}
                        className="flex items-center gap-1.5 px-4 py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg font-bold text-xs transition-colors shadow-sm"
                        title="Download PDF"
                      >
                        <FileDown className="w-4 h-4" />
                        {t.downloadPdf}
                      </button>
                    )}

                    <button className="p-1.5 bg-gray-50 border border-gray-200 rounded-full text-gray-500 hover:bg-gray-100 ml-auto sm:ml-0 transition-colors">
                      {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                    </button>
                  </div>
                </div>

                {/* ======================================= */}
                {/* --- MODERN UI CONTENT --- */}
                {/* ======================================= */}
                {isExpanded && (
                  <div className="border-t border-gray-100 bg-gray-50/30 p-6 md:p-8">
                    
                    {/* --- TOP SECTION: Batch Table --- */}
                    <div className="mb-10 w-full overflow-x-auto custom-scrollbar pb-2">
                      <div className="flex items-center gap-2 mb-4">
                        <Activity className="w-4 h-4 text-blue-500" />
                        <h4 className="text-[11px] font-bold text-gray-500 uppercase tracking-widest">{t.batchQty}</h4>
                      </div>

                      {hasBatches ? (
                        chunkArray(activeBatches, 15).map((chunk, chunkIdx) => (
                          <table key={`table-${chunkIdx}`} className="w-full min-w-max border-collapse border border-gray-200 mb-6 bg-white shadow-sm rounded-lg overflow-hidden">
                            <thead className="bg-gray-50 border-b border-gray-200">
                              <tr>
                                <th className="border-r border-gray-200 text-gray-500 font-bold text-[11px] uppercase px-4 py-2 text-left w-24">
                                  {t.batchNo}
                                </th>
                                {chunk.map(batch => (
                                  <th 
                                    key={`th-${batch.num}`} 
                                    className="border-r border-gray-200 text-blue-600 font-bold text-[13px] px-3 py-2 text-center min-w-[55px] last:border-r-0"
                                  >
                                    {batch.num}
                                  </th>
                                ))}
                              </tr>
                            </thead>
                            <tbody>
                              <tr>
                                <td className="border-r border-gray-200 bg-gray-50 text-gray-500 font-bold text-[11px] uppercase px-4 py-3 text-left w-24">
                                  {t.kg}
                                </td>
                                {chunk.map(batch => (
                                  <td 
                                    key={`td-${batch.num}`} 
                                    className="border-r border-gray-200 text-gray-800 font-bold text-sm px-3 py-3 text-center last:border-r-0"
                                  >
                                    {batch.kg}
                                  </td>
                                ))}
                              </tr>
                            </tbody>
                          </table>
                        ))
                      ) : (
                        <div className="bg-white border border-dashed border-gray-300 rounded-lg p-6 text-center w-full max-w-md">
                          <p className="text-gray-500 font-medium text-sm">{t.noBatches}</p>
                        </div>
                      )}
                    </div>

                    {/* --- BOTTOM SECTION: Info List --- */}
                    <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm">
                      <div className="flex items-center gap-2 mb-6 border-b border-gray-100 pb-4">
                        <Info className="w-4 h-4 text-green-600" />
                        <h4 className="text-[11px] font-bold text-gray-500 uppercase tracking-widest">{t.prodSummary}</h4>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-4 text-sm text-gray-700">
                        <div className="flex justify-between items-center py-1.5 border-b border-gray-50">
                          <span className="font-medium text-gray-500">{t.cropDate}</span>
                          <span className="font-bold text-gray-900">{formattedCropDate}</span>
                        </div>
                        <div className="flex justify-between items-center py-1.5 border-b border-gray-50">
                          <span className="font-medium text-gray-500">{t.mfDate}</span>
                          <span className="font-bold text-gray-900">{formattedMFDate}</span>
                        </div>
                        <div className="flex justify-between items-center py-1.5 border-b border-gray-50">
                          <span className="font-medium text-gray-500">{t.greenLeaf}</span>
                          <span className="font-bold text-blue-600">{consolidated.receivedTotalCropKg || 0} kg</span>
                        </div>
                        <div className="flex justify-between items-center py-1.5 border-b border-gray-50">
                          <span className="font-medium text-gray-500">{t.witherLeaf}</span>
                          <span className="font-bold text-green-600">{consolidated.witheredLeafKg || 0} kg</span>
                        </div>
                        <div className="flex justify-between items-center py-1.5 border-b border-gray-50">
                          <span className="font-medium text-gray-500">{t.witheringP}</span>
                          <span className="font-bold text-gray-900">{consolidated.percentage || 0}%</span>
                        </div>
                        <div className="flex justify-between items-center py-1.5 border-b border-gray-50">
                          <span className="font-medium text-gray-500">{t.quality}</span>
                          <span className="font-bold text-orange-500">{consolidated.weatheringQuality || '-'}</span>
                        </div>
                        <div className="flex justify-between items-center py-1.5 border-b border-gray-50">
                          <span className="font-medium text-gray-500">{t.factory}</span>
                          <span className="font-bold text-gray-900">{consolidated.factory || '-'}</span>
                        </div>
                        <div className="flex justify-between items-center py-1.5 border-b border-gray-50">
                          <span className="font-medium text-gray-500">{t.opsPeriod}</span>
                          <span className="font-bold text-gray-900">
                            {consolidated.startTime || '-'} to {consolidated.finishTime || '-'} ({consolidated.period || '-'})
                          </span>
                        </div>
                      </div>
                    </div>

                  </div>
                )}

                {/* ========================================================= */}
                {/* --- BEAUTIFIED HIDDEN PDF TEMPLATE (MATCHING REFERENCE UI) --- */}
                {/* ========================================================= */}
                <div 
                  id={`pdf-print-area-${groupKey}`}
                  style={{ width: '1122px', minHeight: '793px', display: 'none', backgroundColor: '#ffffff', color: '#111827', padding: '48px', fontFamily: 'sans-serif', boxSizing: 'border-box' }}
                >
                  {/* Top Green Accent Bar */}
                  <div style={{ height: '6px', backgroundColor: '#15803d', width: '100%', marginBottom: '24px', borderRadius: '4px' }}></div>

                  {/* Header */}
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '32px', borderBottom: '2px solid #e5e7eb', paddingBottom: '20px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                      <img 
                        src="/logo.png" 
                        alt="Logo" 
                        style={{ width: '64px', height: '64px', objectFit: 'contain' }} 
                        onError={(e) => e.target.style.display = 'none'} 
                      />
                      <div>
                        <h1 style={{ fontSize: '22px', fontWeight: '800', color: '#15803d', textTransform: 'uppercase', margin: 0, letterSpacing: '0.025em' }}>Athukorala Group (Pvt) Ltd</h1>
                        <h2 style={{ fontSize: '18px', fontWeight: '700', marginTop: '4px', color: '#1f2937', margin: 0 }}>{t.title}</h2>
                        <p style={{ color: '#4b5563', fontSize: '13px', marginTop: '4px', margin: 0 }}>Filter Applied: Date - {formattedCropDate}</p>
                      </div>
                    </div>
                    <div style={{ textAlign: 'right', fontSize: '12px', color: '#6b7280', display: 'flex', flexDirection: 'column', gap: '4px', backgroundColor: '#f9fafb', padding: '12px 16px', borderRadius: '8px', border: '1px solid #e5e7eb' }}>
                      <p style={{ margin: 0 }}><strong style={{ color: '#111827' }}>{t.docRef}:</strong> {docRefCode}</p>
                      <p style={{ margin: 0 }}><strong style={{ color: '#111827' }}>{t.generated}:</strong> {currentTimestamp}</p>
                    </div>
                  </div>

                  {/* Top: Batch Table */}
                  <div style={{ marginBottom: '32px' }}>
                    <h3 style={{ fontSize: '13px', fontWeight: '800', color: '#1d4ed8', textTransform: 'uppercase', marginBottom: '12px', letterSpacing: '0.05em', display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <span style={{ display: 'inline-block', width: '8px', height: '8px', backgroundColor: '#2563eb', borderRadius: '50%' }}></span>
                      {t.batchQty}
                    </h3>
                    {hasBatches ? (
                      chunkArray(activeBatches, 15).map((chunk, cIdx) => (
                        <table key={`pdf-table-${cIdx}`} style={{ width: '100%', borderCollapse: 'collapse', border: '1px solid #cbd5e1', marginBottom: '16px', textAlign: 'center', fontSize: '12px', borderRadius: '8px', overflow: 'hidden' }}>
                          <thead>
                            <tr style={{ backgroundColor: '#eff6ff', color: '#1e3a8a' }}>
                              <th style={{ border: '1px solid #cbd5e1', padding: '10px 14px', fontWeight: '700', textTransform: 'uppercase', textAlign: 'left', width: '100px', fontSize: '11px', letterSpacing: '0.05em' }}>Batch No</th>
                              {chunk.map(b => (
                                <th key={`pdf-th-${b.num}`} style={{ border: '1px solid #cbd5e1', padding: '10px 8px', fontWeight: '700', color: '#1e40af', fontSize: '12px' }}>{b.num}</th>
                              ))}
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td style={{ border: '1px solid #cbd5e1', padding: '10px 14px', fontWeight: '700', textTransform: 'uppercase', textAlign: 'left', backgroundColor: '#f8fafc', color: '#475569', fontSize: '11px' }}>Kg</td>
                              {chunk.map(b => (
                                <td key={`pdf-td-${b.num}`} style={{ border: '1px solid #cbd5e1', padding: '10px 8px', fontWeight: '700', color: '#0f172a', backgroundColor: '#ffffff' }}>{b.kg}</td>
                              ))}
                            </tr>
                          </tbody>
                        </table>
                      ))
                    ) : (
                      <p style={{ fontSize: '13px', color: '#6b7280', fontStyle: 'italic', padding: '12px', backgroundColor: '#f9fafb', borderRadius: '6px', border: '1px dashed #d1d5db' }}>No batches recorded.</p>
                    )}
                  </div>

                  {/* Bottom: Production Summary (Clean 2-Column List Style matching reference image) */}
                  <div style={{ marginBottom: '40px', backgroundColor: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: '12px', padding: '24px' }}>
                    <h3 style={{ fontSize: '13px', fontWeight: '800', color: '#15803d', textTransform: 'uppercase', marginBottom: '16px', letterSpacing: '0.05em', display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <span style={{ display: 'inline-block', width: '8px', height: '8px', backgroundColor: '#16a34a', borderRadius: '50%' }}></span>
                      {t.prodSummary}
                    </h3>
                    
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px 32px', fontSize: '14px', color: '#334155' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #e2e8f0' }}>
                        <span style={{ fontWeight: '500', color: '#64748b' }}>Crop Date</span>
                        <span style={{ fontWeight: '700', color: '#0f172a' }}>{formattedCropDate}</span>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #e2e8f0' }}>
                        <span style={{ fontWeight: '500', color: '#64748b' }}>M/F Date</span>
                        <span style={{ fontWeight: '700', color: '#0f172a' }}>{formattedMFDate}</span>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #e2e8f0' }}>
                        <span style={{ fontWeight: '500', color: '#64748b' }}>Green Leaf</span>
                        <span style={{ fontWeight: '800', color: '#2563eb' }}>{consolidated.receivedTotalCropKg || 0} kg</span>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #e2e8f0' }}>
                        <span style={{ fontWeight: '500', color: '#64748b' }}>Wither Leaf</span>
                        <span style={{ fontWeight: '800', color: '#16a34a' }}>{consolidated.witheredLeafKg || 0} kg</span>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #e2e8f0' }}>
                        <span style={{ fontWeight: '500', color: '#64748b' }}>Withering (P)</span>
                        <span style={{ fontWeight: '700', color: '#0f172a' }}>{consolidated.percentage || 0}%</span>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #e2e8f0' }}>
                        <span style={{ fontWeight: '500', color: '#64748b' }}>Quality</span>
                        <span style={{ fontWeight: '800', color: '#ea580c' }}>{consolidated.weatheringQuality || '-'}</span>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #e2e8f0' }}>
                        <span style={{ fontWeight: '500', color: '#64748b' }}>Factory</span>
                        <span style={{ fontWeight: '700', color: '#0f172a' }}>{consolidated.factory || '-'}</span>
                      </div>
                      <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '10px', borderBottom: '1px solid #e2e8f0' }}>
                        <span style={{ fontWeight: '500', color: '#64748b' }}>Ops Period</span>
                        <span style={{ fontWeight: '700', color: '#0f172a' }}>{consolidated.startTime || '-'} to {consolidated.finishTime || '-'} ({consolidated.period || '-'})</span>
                      </div>
                    </div>
                  </div>

                  {/* Footer */}
                  <div style={{ marginTop: '48px', paddingTop: '20px', borderTop: '2px solid #e5e7eb', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', fontSize: '13px', fontWeight: '700', color: '#374151' }}>
                    <div>
                      <p style={{ color: '#9ca3af', fontWeight: 'normal', fontSize: '11px', margin: 0, marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{t.genBy}</p>
                      <p style={{ color: '#111827', margin: 0, fontSize: '14px' }}>{currentUsername} ({userRole})</p>
                    </div>
                    <div style={{ textAlign: 'center' }}>
                      <p style={{ color: '#cbd5e1', margin: 0, marginBottom: '4px', letterSpacing: '2px' }}>.................................................................</p>
                      <p style={{ color: '#9ca3af', fontWeight: 'normal', fontSize: '11px', margin: 0, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{t.authSig}</p>
                    </div>
                  </div>
                </div>

              </div>
            );
          })
        )}
      </div>
    </div>
  );
};

export default WitherLeafSummary;