import React, { useState, useEffect, useMemo, useRef } from "react";
import toast from "react-hot-toast";
import { FileSpreadsheet, Calendar, Languages, FileDown, RefreshCw } from "lucide-react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

const ROUTE_ORDER = [
  "E - ESTATE TEA", "FA - FACTORY", 
  "C1 - MATHTHAKA", "C2 - WALALLAWITA", "C3 - PELAWATHTHA", "C4 - POLGAMPALA",
  "C5 - MANAMPITA", "C7 - GANEGODA", "C8 - THUNDOLA"
];

export default function CollectorQualityDiffReport() {
  const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;
  const currentUsername = localStorage.getItem("username") || "Unknown User";
  const userRole = localStorage.getItem("userRole") || "";
  const [selectedDate, setSelectedDate] = useState(() => new Date().toISOString().split('T')[0]);
  
  const [weekData, setWeekData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [lang, setLang] = useState("SI");

  const printAreaRef = useRef(null);

  // 💡 --- WEEK CALCULATION (Thursday to Wednesday) ---
  const weekDates = useMemo(() => {
    const d = new Date(selectedDate);
    const dayOfWeek = d.getDay(); 
    const diffToThursday = (dayOfWeek < 4 ? dayOfWeek + 7 : dayOfWeek) - 4;
    
    const startDate = new Date(d);
    startDate.setDate(d.getDate() - diffToThursday);

    const dates = [];
    for (let i = 0; i < 7; i++) {
      const tempDate = new Date(startDate);
      tempDate.setDate(startDate.getDate() + i);
      dates.push(tempDate.toISOString().split('T')[0]);
    }
    return dates;
  }, [selectedDate]);

  // 💡 --- TRANSLATIONS ---
  const t = {
    pageTitle: lang === 'SI' ? "දළු එකතු කරන්නාගේ ගුණාත්මය හා වෙනස" : "Collector Quality & Difference",
    reportTitle: lang === 'SI' ? "දළු එකතු කරන්නාගේ ගුණාත්මය හා වෙනස පිළිබඳ වාර්තාව" : "Collector Quality & Difference Report",
    monthDate: lang === 'SI' ? "මාසය" : "Month",
    supplier: lang === 'SI' ? "සැපයුම්කරුගේ නම" : "Supplier Name",
    diff: "DIFF",
    saturday: lang === 'SI' ? "සෙනසුරාදා" : "SATURDAY",
    holiday: lang === 'SI' ? "නිවාඩු" : "HOLIDAY",
    signGen: lang === 'SI' ? "සකස් කළේ:" : "Generated By:",
    signFac: lang === 'SI' ? "කර්මාන්තශාලා නිලධාරී" : "Factory Officer",
    signChair: lang === 'SI' ? "සභාපති" : "Chairman",
    docRef: lang === 'SI' ? "ලේඛන අංකය " : "Doc Ref ",
    genTime: lang === 'SI' ? "වේලාව " : "Generated ",
    dateRange: lang === 'SI' ? "සතිය: " : "Week: ",
    to: lang === 'SI' ? "සිට: " : "to: ",
  };

  const now = new Date();
  const generatedDateTime = `${now.getFullYear()}/${String(now.getMonth() + 1).padStart(2, '0')}/${String(now.getDate()).padStart(2, '0')} ${now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }).toLowerCase()}`;
  const uniqueCode = `COL-DIFF/${selectedDate.replace(/-/g, '')}`;

  // 💡 --- FETCH DATA ---
  const fetchWeekData = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem("token");
      const headers = { Authorization: `Bearer ${token}` };

      const promises = weekDates.map(date => 
        fetch(`${BACKEND_URL}/api/factory-loft-leaf/report?date=${date}`, { headers })
          .then(res => res.ok ? res.json() : { data: [] })
          .catch(() => ({ data: [] }))
      );

      const results = await Promise.all(promises);
      
      let combinedRecords = [];
      results.forEach((res, index) => {
          (res.data || []).forEach(r => combinedRecords.push({ ...r, _recordDate: weekDates[index] }));
      });

      setWeekData(combinedRecords);
    } catch (error) {
      console.error("Fetch error:", error);
      toast.error("Failed to load records.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchWeekData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedDate]); 

  // 💡 --- PROCESS DATA (Collector Data + Diff) ---
  const processedTable = useMemo(() => {
      const routeMap = {};

      ROUTE_ORDER.forEach(route => {
        routeMap[route] = {
          name: route.split(' - ')[0], 
          fullName: lang === 'SI' ? getSinhalaRouteName(route) : route,
          days: {}
        };
      });

      weekData.forEach(record => {
         const routeStr = record.route;
         
         // අපි මෙහිදී ප්‍රධාන වශයෙන් ගන්නේ Collector Sample එකයි
         const colSample = record.collectorSample?.isEntered ? record.collectorSample : null;
         const facSample = record.factorySample?.isEntered ? record.factorySample : null;
         
         if (colSample && routeMap[routeStr]) {
             const b = Number(colSample.bestPct || 0);
             const bb = Number(colSample.belowBestPct || 0);
             const p = Number(colSample.poorPct || 0);
             
             let diff = "-";
             // Factory දත්ත තිබේ නම් Difference එක ගණනය කිරීම (Collector Best - Factory Best)
             if (facSample) {
                 const facB = Number(facSample.bestPct || 0);
                 diff = b - facB;
             }

             routeMap[routeStr].days[record._recordDate] = { b, bb, p, diff };
         }
      });

      return Object.values(routeMap).filter(r => r.name !== 'E'); // Estate ඉවත් කර ඇත
  }, [weekData, lang]);

  function getSinhalaRouteName(route) {
      if (route.includes("FACTORY")) return "කුඩා තේ ඉඩම් හිමියන්";
      if (route.includes("C1")) return "C1 - මත්තක";
      if (route.includes("C2")) return "C2 - වළල්ලාවිට";
      if (route.includes("C3")) return "C3 - පැලවත්ත";
      if (route.includes("C4")) return "C4 - පොල්ගම්පල";
      if (route.includes("C5")) return "C5 - මානම්පිට";
      if (route.includes("C7")) return "C7 - ගනේගොඩ";
      if (route.includes("C8")) return "C8 - තුන්දොළ";
      return route;
  }

  const generatePDF = async () => {
    const toastId = toast.loading("Generating Report...");
    try {
        const printElement = printAreaRef.current;
        printElement.style.display = "block";
        printElement.style.position = "absolute";
        printElement.style.top = "-99999px"; 
        printElement.style.width = "1500px"; // Wide enough for 4 columns per day

        const canvas = await html2canvas(printElement, { scale: 2, useCORS: true, backgroundColor: "#ffffff" });

        printElement.style.display = "none"; 
        printElement.style.width = "";
        
        const pdf = new jsPDF('landscape', 'pt', 'a4');
        const pdfW = pdf.internal.pageSize.getWidth();
        const pdfH = pdf.internal.pageSize.getHeight();
        const margin = 20; 
        const maxW = pdfW - (margin * 2);
        const maxH = pdfH - (margin * 2);

        const imgData = canvas.toDataURL('image/jpeg', 1.0); 
        let finalW = maxW;
        let finalH = (canvas.height * finalW) / canvas.width;

        if (finalH > maxH) {
            finalH = maxH;
            finalW = (canvas.width * finalH) / canvas.height;
        }

        pdf.addImage(imgData, 'JPEG', (pdfW - finalW)/2, margin, finalW, finalH);

         const pageCount = pdf.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            pdf.setPage(i);
            pdf.setFontSize(8);
            pdf.setTextColor(128, 128, 128);
            pdf.text(`Page ${i} of ${pageCount} - Generated by Unified Management System`, pdfW / 2, pdfH - 15, { align: 'center' });
        }

        pdf.save(`Collector_Diff_Report_${weekDates[0]}.pdf`);
        toast.success("Report downloaded successfully!", { id: toastId });

    } catch (error) {
        console.error(error);
        toast.error("Failed to generate PDF.", { id: toastId });
    }
  };

  return (
    <div className="p-4 sm:p-8 max-w-[1600px] mx-auto font-sans min-h-screen flex flex-col transition-colors duration-300">
      
      {/* --- HEADER --- */}
      <div className="mb-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white dark:bg-zinc-900 p-5 rounded-2xl shadow-sm border border-gray-200 dark:border-zinc-800">
        <div>
          <h2 className="text-2xl font-bold text-[#3f6212] dark:text-lime-500 flex items-center gap-2">
            <FileSpreadsheet size={24} /> {t.pageTitle}
          </h2>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
            {t.dateRange} <span className="font-bold text-[#65a30d]">{weekDates[0]}</span> to <span className="font-bold text-[#65a30d]">{weekDates[6]}</span>
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
          <button onClick={() => setLang(lang === 'EN' ? 'SI' : 'EN')} className="p-2.5 px-4 bg-indigo-50 text-indigo-700 hover:bg-indigo-100 border border-indigo-200 rounded-lg font-bold text-sm flex items-center gap-2">
            <Languages size={18} /> {lang === 'EN' ? "සිංහල" : "English"}
          </button>
          
          <div className="relative">
            <Calendar size={18} className="absolute left-3 top-3 text-[#65a30d]" />
            <input 
              type="date" 
              value={selectedDate} 
              onChange={(e) => setSelectedDate(e.target.value)}
              className="pl-10 pr-4 py-2.5 border border-lime-200 rounded-lg text-sm font-bold outline-none bg-lime-50/30 text-[#3f6212] cursor-pointer"
            />
          </div>

          <button onClick={generatePDF} disabled={loading || processedTable.length === 0} className="p-2.5 px-4 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-bold text-sm disabled:opacity-50 flex items-center gap-2">
            <FileDown size={18} /> Download PDF
          </button>

          <button onClick={fetchWeekData} disabled={loading} className="p-2.5 bg-gray-100 hover:bg-gray-200 text-gray-600 rounded-lg">
            <RefreshCw size={18} className={loading ? "animate-spin" : ""} />
          </button>
        </div>
      </div>

      {/* --- UI VIEW (Screen) --- */}
      <div className="bg-white dark:bg-zinc-900 rounded-2xl shadow-sm border border-gray-200 overflow-x-auto p-1 custom-scrollbar">
        {loading ? (
            <div className="p-16 text-center text-gray-500 font-bold">Loading Data...</div>
        ) : (
            <div className="p-2">
                <table className="w-full border-collapse border border-[#cbd5e1] text-center text-[12px] sm:text-[14px]">
                   <thead>
                       <tr>
                           <th rowSpan={2} className="text-center border border-[#cbd5e1] p-1.5 font-bold bg-[#D8FDE4] text-[#374151] w-[12%]">
                               {t.monthDate}<br/><hr className="my-1 border-[#cbd5e1]"/>{t.supplier}
                           </th>
                           {weekDates.map(date => (
                               <th key={date} colSpan={4} className="border border-[#cbd5e1] p-1.5 font-bold bg-[#D8FDE4] text-[#1d4ed8]">
                                   {date.split('-').slice(1).join('/')}
                               </th>
                           ))}
                       </tr>
                       <tr className="bg-[#e5e7eb]">
                           {weekDates.map((_, i) => (
                               <React.Fragment key={i}>
                                   <th className="border border-[#cbd5e1] bg-[#D8FDE4] p-1 font-bold text-[#16a34a]">B</th>
                                   <th className="border border-[#cbd5e1] bg-[#D8FDE4] p-1 font-bold text-[#ca8a04]">B/B</th>
                                   <th className="border border-[#cbd5e1] bg-[#D8FDE4] p-1 font-bold text-[#1f2937]">P</th>
                                   <th className="border border-[#cbd5e1] bg-[#fee2e2] p-1 font-bold text-[#dc2626]">{t.diff}</th>
                               </React.Fragment>
                           ))}
                       </tr>
                   </thead>
                   <tbody className="bg-white dark:bg-zinc-950">
                       {processedTable.map((route, idx) => (
                               <tr key={idx} className="hover:bg-gray-50">
                                   <td className="border border-[#cbd5e1] p-1.5 text-left bg-[#f8fafc] text-[#000000] truncate">
                                       {route.fullName}
                                   </td>
                                   {weekDates.map(date => {
                                       const d = route.days[date];
                                       const dayOfWeek = new Date(date).getDay();
                                       const isWeekendEmpty = (dayOfWeek === 6 || dayOfWeek === 0) && !processedTable.some(r => r.days[date]);

                                       if (isWeekendEmpty) {
                                           if (idx === 0) {
                                               return (
                                                   <td key={date} rowSpan={processedTable.length} colSpan={4} className="border border-[#cbd5e1] p-2 text-center font-bold text-[#6b7280] bg-[#f8fafc] text-[13px] tracking-widest align-middle">
                                                       {dayOfWeek === 6 ? t.saturday : t.holiday}
                                                   </td>
                                               );
                                           }
                                           return null; 
                                       }

                                       if (!d) {
                                           return (
                                               <React.Fragment key={date}>
                                                   <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                                   <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                                   <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                                   <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                               </React.Fragment>
                                           );
                                       }

                                       return (
                                           <React.Fragment key={date}>
                                               <td className="border border-[#cbd5e1] p-1.5 text-[#1f2937]">{d.b}</td>
                                               <td className="border border-[#cbd5e1] p-1.5 text-[#1f2937]">{d.bb}</td>
                                               <td className="border border-[#cbd5e1] p-1.5 text-[#1f2937]">{d.p}</td>
                                               <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#dc2626] bg-[#fef2f2]">{d.diff}</td>
                                           </React.Fragment>
                                       );
                                   })}
                               </tr>
                       ))}
                   </tbody>
                </table>
            </div>
        )}
      </div>

      {/* ========================================================================================= */}
      {/* 💡 HIDDEN PRINT AREA FOR PDF DIRECT DOWNLOAD */}
      {/* ========================================================================================= */}
      <div id="pdf-print-area" ref={printAreaRef} style={{ display: 'none' }}>
          <div className="bg-[#ffffff] p-8 font-sans text-[#000000] flex flex-col justify-between" style={{ minHeight: '1000px' }}>
              
              <div>
                  {/* Header */}
                  <div className="flex justify-between items-start mb-8 border-b border-[#d1d5db] pb-4">
                      <div className="flex items-center gap-4">
                          <img src="/logo.png" alt="Logo" className="w-20 h-20 object-contain" onError={(e) => e.target.style.display = 'none'} />
                          <div>
                              <h1 className="text-3xl font-bold text-[#1B6A31] uppercase" style={{ fontFamily: 'sans-serif' }}>
                                  Athukorala Group (Pvt) Ltd
                              </h1>
                              <h2 className="text-2xl font-bold mt-2" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                                  {t.reportTitle}
                              </h2>
                              <p className="text-xl mt-1" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                                  {t.dateRange} 
                                  <span className="font-extrabold text-[#4d7c0f] tracking-wide ml-2">{weekDates[0]}</span> 
                                  <span className="mx-2 font-medium">{t.to}</span> 
                                  <span className="font-extrabold text-[#4d7c0f] tracking-wide">{weekDates[6]}</span>
                              </p>
                          </div>
                      </div>
                      <div className="text-right text-sm text-[#6b7280] flex flex-col gap-1.5" style={{ fontFamily: 'sans-serif' }}>
                          <p><strong className="text-[#4b5563]">{t.docRef}:</strong> {uniqueCode}</p>
                          <p><strong className="text-[#4b5563]">{t.genTime}:</strong> {generatedDateTime}</p>
                      </div>
                  </div>

                  {/* Main Table */}
                  <table className="w-full table-fixed border-collapse border border-[#cbd5e1] text-center text-[15px]" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                      <thead>
                          <tr>
                              <th rowSpan={2} className="text-center border border-[#cbd5e1] p-2.5 font-extrabold bg-[#f3f4f6] text-[#000000] w-[14%]">
                                 {t.supplier}
                              </th>
                              {weekDates.map(date => (
                                  <th key={date} colSpan={4} className="border border-[#cbd5e1] p-2.5 font-extrabold bg-[#D8FDE4] text-[#000000]">
                                      {date.split('-').reverse().join('/')} {/* 13/08/2026 format */}
                                  </th>
                              ))}
                          </tr>
                          <tr>
                              {weekDates.map((_, i) => (
                                  <React.Fragment key={i}>
                                      <th className="border border-[#cbd5e1] bg-[#D8FDE4] p-1.5 font-bold text-[#16a34a]">B</th>
                                      <th className="border border-[#cbd5e1] bg-[#D8FDE4] p-1.5 font-bold text-[#ca8a04]">B/B</th>
                                      <th className="border border-[#cbd5e1] bg-[#D8FDE4] p-1.5 font-bold text-[#dc2626]">P</th>
                                      <th className="border border-[#cbd5e1] bg-[#FFEBEB] p-1.5 font-bold text-[#dc2626]">{t.diff}</th>
                                  </React.Fragment>
                              ))}
                          </tr>
                      </thead>
                      <tbody className="text-center">
                          {processedTable.map((route, idx) => (
                              <tr key={idx}>
                                  <td className="border border-[#cbd5e1] p-2 text-left bg-[#f8fafc] text-[#000000] truncate">
                                      {route.fullName}
                                  </td>
                                  {weekDates.map(date => {
                                      const d = route.days[date];
                                      const dayOfWeek = new Date(date).getDay();
                                      const isWeekendEmpty = (dayOfWeek === 6 || dayOfWeek === 0) && !processedTable.some(r => r.days[date]);

                                      if (isWeekendEmpty) {
                                          if (idx === 0) {
                                              return (
                                                  <td key={date} rowSpan={processedTable.length} colSpan={4} className="border border-[#cbd5e1] p-2 text-center text-[#000000] bg-[#f8fafc] text-[16px] tracking-widest align-middle">
                                                      {dayOfWeek === 6 ? t.saturday : t.holiday}
                                                  </td>
                                              );
                                          }
                                          return null;
                                      }

                                      if (!d) {
                                          return (
                                              <React.Fragment key={date}>
                                                  <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                                  <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                                  <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                                  <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                              </React.Fragment>
                                          );
                                      }

                                      return (
                                          <React.Fragment key={date}>
                                              <td className="border border-[#cbd5e1] p-1.5 text-[#1f2937]">{d.b}</td>
                                              <td className="border border-[#cbd5e1] p-1.5 text-[#1f2937]">{d.bb}</td>
                                              <td className="border border-[#cbd5e1] p-1.5 text-[#1f2937]">{d.p}</td>
                                              <td className="border border-[#cbd5e1] p-1.5 text-[#dc2626] bg-[#FFEBEB] font-bold">{d.diff}</td>
                                          </React.Fragment>
                                      );
                                  })}
                              </tr>
                          ))}
                      </tbody>
                  </table>
              </div>
              
              {/* FOOTER SIGNATURES */}
              <div className="mt-16 pt-8 w-full flex flex-row justify-between px-16 items-end text-[16px] font-bold font-sans text-[#374151]">                  
                  <div className="text-center">
                      <p className="text-[#4b5563] font-sans mb-2">{t.signGen}</p>
                      <p className="text-[#2C3A3A] font-sans">{currentUsername} ({userRole})</p>
                  </div>
                  <div className="text-center">
                      <p className="text-[#4b5563] mb-2">.............................................................</p>
                      <p className="text-[#4b5563]">{t.signFac}</p>
                  </div>
                  <div className="text-center">
                      <p className="text-[#4b5563] mb-2">.............................................................</p>
                      <p className="text-[#4b5563]">{t.signChair}</p>
                  </div>
              </div>

          </div>
      </div>

    </div>
  );
}