import React, { useState, useEffect, useMemo, useRef } from "react";
import toast from "react-hot-toast";
import { FileSpreadsheet, Calendar, Languages, FileDown, RefreshCw, Trophy, History } from "lucide-react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

const ROUTE_ORDER = [
  "E - ESTATE TEA", "FA - FACTORY", 
  "C1 - MATHTHAKA", "C2 - WALALLAWITA", "C3 - PELAWATHTHA", "C4 - POLGAMPALA",
  "C5 - MANAMPITA", "C7 - GANEGODA", "C8 - THUNDOLA"
];

export default function WeeklyLoftLeafSummary() {
  const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;
  const currentUsername = localStorage.getItem("username") || "Unknown User";
  const userRole = localStorage.getItem("userRole") || "";
  const [selectedDate, setSelectedDate] = useState(() => new Date().toISOString().split('T')[0]);
  
  // States for Current & Previous Week Data
  const [weekData, setWeekData] = useState([]);
  const [prevWeekData, setPrevWeekData] = useState([]);
  
  const [loading, setLoading] = useState(false);
  const [lang, setLang] = useState("SI");

  const printAreaRef = useRef(null);

  // 💡 --- WEEK CALCULATION (Current Week: Thursday to Wednesday) ---
  const weekDates = useMemo(() => {
    const d = new Date(selectedDate);
    const dayOfWeek = d.getDay(); 
    const diffToThursday = (dayOfWeek < 4 ? dayOfWeek + 7 : dayOfWeek) - 4;
    
    const startDate = new Date(d);
    startDate.setDate(d.getDate() - diffToThursday);

    const dates = [];
    for (let i = 0; i < 7; i++) {
      const tempDate = new Date(startDate);
      tempDate.setDate(startDate.getDate() + i);
      dates.push(tempDate.toISOString().split('T')[0]);
    }
    return dates;
  }, [selectedDate]);
  
  // 💡 --- WEEK CALCULATION (Previous Week) ---
  const prevWeekDates = useMemo(() => {
    if (!weekDates || weekDates.length === 0) return [];
    return weekDates.map(date => {
        const d = new Date(date);
        d.setDate(d.getDate() - 7); // Go back exactly 7 days
        return d.toISOString().split('T')[0];
    });
  }, [weekDates]);

  // 💡 --- TRANSLATIONS ---
  const t = {
    pageTitle: lang === 'SI' ? "අමු තේ දළු සතිපතා සාරාංශය" : "Weekly Loft Leaf Summary",
    reportTitle: lang === 'SI' ? "අමු තේ (Green Leaf) වල ගුණාත්මය ඇගයීම පිළිබඳ වාර්තාව" : "Green Leaf Quality Evaluation Report",
    monthDate: lang === 'SI' ? "දිනය" : "Date",
    supplier: lang === 'SI' ? "සැපයුම්කරුගේ නම" : "Supplier Name",
    weeklyAvg: lang === 'SI' ? "සාමාන්‍ය අගය" : "Weekly Average",
    rank: lang === 'SI' ? "ස්ථානය" : "Rank",
    legendRed: lang === 'SI' ? "ගුණාත්මය 55% ට අඩු" : "Quality < 55%",
    legendGreen: lang === 'SI' ? "තැළුනු දළු 5% ට වැඩි" : "Damaged > 5%",
    legendYellow: lang === 'SI' ? "මෝරපු දළු 45% ට වැඩි" : "Mature > 45%",
    signGen: lang === 'SI' ? "සකස් කළේ:" : "Generated By:",
    signFac: lang === 'SI' ? "කර්මාන්තශාලා නිලධාරී" : "Factory Officer",
    signChair: lang === 'SI' ? "සභාපති" : "Chairman",
    docRef: lang === 'SI' ? "ලේඛන අංකය " : "Doc Ref ",
    genTime: lang === 'SI' ? "වේලාව " : "Generated ",
    noData: lang === 'SI' ? "තෝරාගත් සතිය සඳහා දත්ත නොමැත." : "No data for selected week.",
    dateRange: lang === 'SI' ? "සතිය: " : "Week: ",
    to: lang === 'SI' ? "සිට: " : "to: ",
    
    route: lang === 'SI' ? "මාර්ගය" : "Route",
    avgBest: lang === 'SI' ? "සාමාන්‍ය Best" : "Avg Best",
    avgBelowBest: lang === 'SI' ? "සාමාන්‍ය B/B" : "Avg Below Best",
    avgPoor: lang === 'SI' ? "සාමාන්‍ය Poor" : "Avg Poor",
    rankTableTitle: lang === 'SI' ? "මෙම සතියේ ශ්‍රේණිගත කිරීම" : "Current Week Ranking",
    prevRankTableTitle: lang === 'SI' ? "පසුගිය සතියේ ශ්‍රේණිගත කිරීම" : "Previous Week Ranking", // 💡 New
    participation: lang === 'SI' ? "සහභාගීත්වය" : "Participation",
    qualityOfficer: lang === 'SI' ? "තත්ත්ව/ කමහල් නිලධාරී" : "Quality / Factory Officer",
    teaInspector: lang === 'SI' ? "තේ උප / පරීක්ෂක" : "Tea Sub / Inspector",
    deputyCommissioner: lang === 'SI' ? "සහකාර නියෝජ්‍ය තේ කොමසාරිස්" : "Asst. Deputy Tea Commissioner",
    registeredProducer: lang === 'SI' ? "ලියාපදිංචි තේ නිෂ්පාදක" : "Registered Tea Producer",
    footerText: lang === 'SI' ? "(මෙය සතිපතා තොරතුරු ලබා ගැනීම සඳහා දිනපතා සම්පූර්ණ කළයුතු ආකෘතියකි)" : "(This format must be completed daily to obtain weekly information)",
    grandAvgLabel: lang === 'SI' ? "කමහලේ දිනයේ සාමාන්‍ය අගය" : "Factory Daily Average",
    saturday: lang === 'SI' ? "සෙනසුරාදා" : "Saturday",
    holiday: lang === 'SI' ? "නිවාඩු" : "Holiday",
    withoutestate: lang === 'SI' ? "කුරුදුවත්ත නොමැතිව" : "Without Estate",
    withestate: lang === 'SI' ? "කුරුදුවත්ත සමග" : "With Estate",
};

  const now = new Date();
  const generatedDateTime = `${now.getFullYear()}/${String(now.getMonth() + 1).padStart(2, '0')}/${String(now.getDate()).padStart(2, '0')} ${now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }).toLowerCase()}`;
  const uniqueCode = `WLLQ-REP/${selectedDate.replace(/-/g, '')}`;

  // 💡 --- FETCH DATA FOR BOTH WEEKS ---
  const fetchWeekData = async () => {
    setLoading(true);
    try {
      const token = localStorage.getItem("token");
      const headers = { Authorization: `Bearer ${token}` };

      // Current week promises
      const currentPromises = weekDates.map(date => 
        fetch(`${BACKEND_URL}/api/factory-loft-leaf/report?date=${date}`, { headers }).then(res => res.ok ? res.json() : { data: [] }).catch(() => ({ data: [] }))
      );

      // Previous week promises
      const prevPromises = prevWeekDates.map(date => 
        fetch(`${BACKEND_URL}/api/factory-loft-leaf/report?date=${date}`, { headers }).then(res => res.ok ? res.json() : { data: [] }).catch(() => ({ data: [] }))
      );

      const [currentResults, prevResults] = await Promise.all([
          Promise.all(currentPromises),
          Promise.all(prevPromises)
      ]);
      
      let combinedRecords = [];
      currentResults.forEach((res, index) => {
          (res.data || []).forEach(r => combinedRecords.push({ ...r, _recordDate: weekDates[index] }));
      });

      let prevCombinedRecords = [];
      prevResults.forEach((res, index) => {
          (res.data || []).forEach(r => prevCombinedRecords.push({ ...r, _recordDate: prevWeekDates[index] }));
      });

      setWeekData(combinedRecords);
      setPrevWeekData(prevCombinedRecords);

    } catch (error) {
      console.error("Fetch error:", error);
      toast.error("Failed to load weekly records.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchWeekData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedDate]); 

  // 💡 --- REUSABLE DATA PROCESSING FUNCTION ---
  // 💡 --- REUSABLE DATA PROCESSING FUNCTION ---
  const processWeeklyStats = (dataArray) => {
      const routeMap = {};

      ROUTE_ORDER.forEach(route => {
        routeMap[route] = {
          name: route.split(' - ')[0], 
          fullName: lang === 'SI' ? getSinhalaRouteName(route) : route,
          days: {},
          totals: { b: 0, bb: 0, p: 0, count: 0 },
          avg: { b: 0, bb: 0, p: 0 },
          rank: "-"
        };
      });

      dataArray.forEach(record => {
         const routeStr = record.route;
         const sample = record.factorySample?.isEntered ? record.factorySample : (record.collectorSample?.isEntered ? record.collectorSample : null);
         
         if (sample && routeMap[routeStr]) {
             const b = Number(sample.bestPct || 0);
             const bb = Number(sample.belowBestPct || 0);
             const p = Number(sample.poorPct || 0);

             routeMap[routeStr].days[record._recordDate] = { b, bb, p };
             routeMap[routeStr].totals.b += b;
             routeMap[routeStr].totals.bb += bb;
             routeMap[routeStr].totals.p += p;
             routeMap[routeStr].totals.count += 1;
         }
      });

      Object.values(routeMap).forEach(route => {
          if (route.totals.count > 0) {
              const rawB = route.totals.b / route.totals.count;
              const rawBB = route.totals.bb / route.totals.count;

              // 💡 Floating point ගැටලුව නිරාකරණය කර නිවැරදිව රවුම් කිරීම (e.g. 36.5 -> 37)
              const b = Math.round(Number(rawB.toFixed(2)));
              const bb = Math.round(Number(rawBB.toFixed(2)));
              
              const p = Math.max(0, 100 - b - bb); 
              
              route.avg.b = b;
              route.avg.bb = bb;
              route.avg.p = p;
          }
      });

      const routesToRank = Object.values(routeMap).filter(r => r.name !== 'E' && r.totals.count > 0);
      routesToRank.sort((a, b) => {
          if (b.avg.b !== a.avg.b) return b.avg.b - a.avg.b; 
          if (b.avg.bb !== a.avg.bb) return b.avg.bb - a.avg.bb; 
          return a.name.localeCompare(b.name); 
      });
      
      let currentRank = 1;
      routesToRank.forEach((r, idx) => {
          if (idx > 0 && r.avg.b === routesToRank[idx - 1].avg.b && r.avg.bb === routesToRank[idx - 1].avg.bb) {
               r.rank = routesToRank[idx - 1].rank; 
          } else {
               r.rank = currentRank; 
          }
          currentRank++; 
      });

      return Object.values(routeMap);
  };

  const processedTable = useMemo(() => processWeeklyStats(weekData), [weekData, lang]);
  const prevProcessedTable = useMemo(() => processWeeklyStats(prevWeekData), [prevWeekData, lang]);

 // 💡 --- (GRAND AVERAGES) පොදු Function එක ---
  // excludeEstate: true නම් Estate Tea (E) අත්හරිනවා
  // 💡 වෙනස: දැන් මෙයට ලබා දෙන්නේ Raw Data නොව, Process කළ Route Averages අඩංගු Array එකයි (processedData)
  const calculateGrandAvg = (processedData, excludeEstate = false) => {
    let totalB = 0, totalBB = 0, count = 0;
    
    processedData.forEach(route => {
         // Estate ඉවත් කිරීම
         if (excludeEstate && route.name === 'E') return; 

         // අදාළ මාර්ගයට දත්ත තිබේ නම් පමණක් එම මාර්ගයේ සාමාන්‍ය අගය එකතු කිරීම
         if (route.totals.count > 0) {
             totalB += route.avg.b;
             totalBB += route.avg.bb;
             count += 1;
         }
    });

    if (count === 0) return { b: "-", bb: "-", p: "-" };
    
    // Math.round() මඟින් 36.5 ➔ 37, 36.12 ➔ 36 ලෙස ආසන්නතම පූර්ණ සංඛ්‍යාවට සකසයි
    const b = Math.round(totalB / count);
    const bb = Math.round(totalBB / count);
    
    // Total එක අනිවාර්යයෙන්ම 100ක් වීමට P අගය Balance කිරීම
    const p = Math.max(0, 100 - b - bb);
    
    return { b, bb, p };
  };

  // 💡 Main Table එක සහ අනෙකුත් පැරණි තැන් සඳහා
  const grandAverages = useMemo(() => calculateGrandAvg(processedTable, false), [processedTable]);
  const prevGrandAverages = useMemo(() => calculateGrandAvg(prevProcessedTable, false), [prevProcessedTable]); 

  // 💡 Ranking වගු යටතට (With Estate & Without Estate)
  const avgCurrentWithE = useMemo(() => calculateGrandAvg(processedTable, false), [processedTable]);
  const avgCurrentNoE = useMemo(() => calculateGrandAvg(processedTable, true), [processedTable]);

  const avgPrevWithE = useMemo(() => calculateGrandAvg(prevProcessedTable, false), [prevProcessedTable]);
  const avgPrevNoE = useMemo(() => calculateGrandAvg(prevProcessedTable, true), [prevProcessedTable]);

  // 💡 --- RANKING TABLE DATA (C1 සිට C8 දක්වා සහ FA අවසානයට සකස් කිරීම) ---
  const getRankingSortIndex = (name) => {
      if (name === "FA") return 999; // FA සෑම විටම අවසානයට යැවීම
      return ROUTE_ORDER.findIndex(r => r.split(' - ')[0] === name);
  };

  const rankTableData = useMemo(() => {
      return processedTable
          .filter(r => r.rank !== "-" && r.name !== "E")
          .sort((a, b) => getRankingSortIndex(a.name) - getRankingSortIndex(b.name));
  }, [processedTable]);

  const prevRankTableData = useMemo(() => {
      return prevProcessedTable
          .filter(r => r.rank !== "-" && r.name !== "E")
          .sort((a, b) => getRankingSortIndex(a.name) - getRankingSortIndex(b.name));
  }, [prevProcessedTable]);

  function getSinhalaRouteName(route) {
      if (route.includes("ESTATE")) return "කුරුඳුවත්ත";
      if (route.includes("FACTORY")) return "කුඩා තේ ඉඩම් හිමියන්";
      if (route.includes("C1")) return "C1 - මත්තක";
      if (route.includes("C2")) return "C2 - වළල්ලාවිට";
      if (route.includes("C3")) return "C3 - පැලවත්ත";
      if (route.includes("C4")) return "C4 - පොල්ගම්පල";
      if (route.includes("C5")) return "C5 - මානම්පිට";
      if (route.includes("C7")) return "C7 - ගනේගොඩ";
      if (route.includes("C8")) return "C8 - තුන්දොළ";
      return route;
  }

  function getCellStyle(type, value) {
      if (value === undefined || value === null || value === 0) return "";
      if (type === 'B' && value < 55) return "bg-[#ffcccc] text-[#cc0000] "; 
      if (type === 'BB' && value > 5) return "bg-[#dcfce7] text-[#15803d] "; 
      if (type === 'P' && value > 45) return "bg-[#fef08a] text-[#a16207] "; 
      return " text-gray-800 dark:text-gray-200";
  }

  const generatePDF = async () => {
    const toastId = toast.loading("Generating Weekly Report (2 Pages)...");
    try {
        const printElement = printAreaRef.current;
        printElement.style.display = "block";
        printElement.style.position = "absolute";
        printElement.style.top = "-99999px"; // තිරයෙන් පිටතට ගෙන යාම

        // 1 වන පිටුව Capture කිරීම
        const page1 = document.getElementById('pdf-page-1');
        const canvas1 = await html2canvas(page1, { scale: 2, useCORS: true, backgroundColor: "#ffffff" });

        // 2 වන පිටුව Capture කිරීම
        const page2 = document.getElementById('pdf-page-2');
        const canvas2 = await html2canvas(page2, { scale: 2, useCORS: true, backgroundColor: "#ffffff" });

        printElement.style.display = "none"; 
        
        const pdf = new jsPDF('landscape', 'pt', 'a4');
        const pdfW = pdf.internal.pageSize.getWidth();
        const pdfH = pdf.internal.pageSize.getHeight();
        const margin = 20; 
        const maxW = pdfW - (margin * 2);
        const maxH = pdfH - (margin * 2);

        // PDF එකට Canvas එක් කිරීමේ පොදු Function එක
        const addCanvasToPdf = (canvas) => {
            const imgData = canvas.toDataURL('image/jpeg', 1.0); 
            let finalW = maxW;
            let finalH = (canvas.height * finalW) / canvas.width;
            if (finalH > maxH) {
                finalH = maxH;
                finalW = (canvas.width * finalH) / canvas.height;
            }
            pdf.addImage(imgData, 'JPEG', (pdfW - finalW)/2, margin, finalW, finalH);
        };

        // පිටු 2 PDF එකට ඇතුළත් කිරීම
        addCanvasToPdf(canvas1);
        pdf.addPage();
        addCanvasToPdf(canvas2);

        // පිටු අංක යෙදීම
        const pageCount = pdf.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            pdf.setPage(i);
            pdf.setFontSize(8);
            pdf.setTextColor(128, 128, 128);
            pdf.text(`Page ${i} of ${pageCount} - Generated by Unified Management System`, pdfW / 2, pdfH - 20, { align: 'center' });
        }

        pdf.save(`Weekly_Quality_Report_${weekDates[0]}.pdf`);
        toast.success("Report downloaded successfully!", { id: toastId });

    } catch (error) {
        console.error(error);
        toast.error("Failed to generate PDF.", { id: toastId });
    }
  };

 return (
    <div className="p-4 sm:p-8 max-w-[1600px] mx-auto font-sans min-h-screen flex flex-col transition-colors duration-300">
      
      {/* --- HEADER --- */}
      <div className="mb-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white dark:bg-zinc-900 p-5 rounded-2xl shadow-sm border border-gray-200 dark:border-zinc-800">
        <div>
          <h2 className="text-2xl font-bold text-[#3f6212] dark:text-lime-500 flex items-center gap-2">
            <FileSpreadsheet size={24} /> {t.pageTitle}
          </h2>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
            {t.dateRange} <span className="font-bold text-[#65a30d] dark:text-lime-400">{weekDates[0]}</span> to <span className="font-bold text-[#65a30d] dark:text-lime-400">{weekDates[6]}</span>
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3 w-full md:w-auto">
          <button onClick={() => setLang(lang === 'EN' ? 'SI' : 'EN')} className="p-2.5 px-4 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-400 hover:bg-indigo-100 dark:hover:bg-indigo-900/50 border border-indigo-200 dark:border-indigo-800 rounded-lg font-bold text-sm flex items-center gap-2 transition-colors">
            <Languages size={18} /> {lang === 'EN' ? "සිංහල" : "English"}
          </button>
          
          <div className="relative">
            <Calendar size={18} className="absolute left-3 top-3 text-[#65a30d] dark:text-lime-500" />
            <input 
              type="date" 
              value={selectedDate} 
              onChange={(e) => setSelectedDate(e.target.value)}
              className="pl-10 pr-4 py-2.5 border border-lime-200 dark:border-zinc-700 rounded-lg text-sm font-bold focus:ring-2 focus:ring-[#84cc16] dark:focus:ring-lime-600 outline-none bg-lime-50/30 dark:bg-zinc-800 text-[#3f6212] dark:text-lime-400 cursor-pointer"
            />
          </div>

          <button onClick={generatePDF} disabled={loading || processedTable.length === 0} className="p-2.5 px-4 bg-blue-600 hover:bg-blue-700 dark:bg-blue-600 dark:hover:bg-blue-500 text-white rounded-lg transition-colors font-bold text-sm disabled:opacity-50 flex items-center gap-2 shadow-sm">
            <FileDown size={18} /> Download PDF
          </button>

          <button onClick={fetchWeekData} disabled={loading} className="p-2.5 bg-gray-100 hover:bg-gray-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-gray-600 dark:text-gray-300 rounded-lg transition-colors">
            <RefreshCw size={18} className={loading ? "animate-spin" : ""} />
          </button>
        </div>
      </div>

      {/* --- UI VIEW (Screen) --- */}
      <div className="bg-white dark:bg-zinc-900 rounded-2xl shadow-sm border border-gray-200 dark:border-zinc-800 overflow-x-auto p-1 custom-scrollbar">
        {/* Legend */}
        <div className="mt-3 mb-3 p-4 bg-gray-50 dark:bg-zinc-800/50 rounded-xl flex flex-wrap gap-8 text-xs font-bold text-gray-600 dark:text-gray-400 border border-gray-200 dark:border-zinc-800">
            <div className="flex items-center gap-2"><span className="w-4 h-4 bg-[#ffcccc] border border-red-300 inline-block rounded"></span> {t.legendRed}</div>
            <div className="flex items-center gap-2"><span className="w-4 h-4 bg-[#dcfce7] border border-green-300 inline-block rounded"></span> {t.legendGreen}</div>
            <div className="flex items-center gap-2"><span className="w-4 h-4 bg-[#fef08a] border border-yellow-300 inline-block rounded"></span> {t.legendYellow}</div>
        </div>

        {loading ? (
            <div className="p-16 text-center text-gray-500 dark:text-gray-400 font-bold">Loading Week Data...</div>
        ) : (
            <div className="p-2">
                <table className="w-full table-fixed border-collapse border border-[#cbd5e1] dark:border-zinc-700 text-center text-[14px]">
                   <thead>
                       <tr>
                           <th rowSpan={2} className="text-center border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold bg-[#f3f4f6] dark:bg-zinc-800 text-[#000000] dark:text-gray-200 w-[15%]">
                               {t.monthDate}<br/><hr className="my-1 border-[#cbd5e1] dark:border-zinc-600"/>{t.supplier}
                           </th>
                           {weekDates.map(date => (
                               <th key={date} colSpan={3} className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold bg-[#eff6ff] dark:bg-blue-900/20 text-[#1d4ed8] dark:text-blue-400">
                                   {date.split('-').slice(1).join('/')}
                               </th>
                           ))}
                           <th colSpan={3} className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold bg-[#f0fdf4] dark:bg-green-900/20 text-[#15803d] dark:text-green-500 whitespace-nowrap">
                               {t.weeklyAvg}
                           </th>
                           <th rowSpan={2} className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold bg-[#f3f4f6] dark:bg-zinc-800 text-[#1d4ed8] dark:text-blue-400 w-[6%]">
                               {t.rank}
                           </th>
                       </tr>
                       <tr className="bg-[#e5e7eb] dark:bg-zinc-800/80">
                           {weekDates.map((_, i) => (
                               <React.Fragment key={i}>
                                   <th className="border border-[#cbd5e1] dark:border-zinc-700 bg-[#eff6ff] dark:bg-blue-900/20 p-1 font-bold text-[#16a34a] dark:text-green-500 w-[3.1%]">B</th>
                                   <th className="border border-[#cbd5e1] dark:border-zinc-700 bg-[#eff6ff] dark:bg-blue-900/20 p-1 font-bold text-[#ca8a04] dark:text-yellow-500 w-[3.1%]">B/B</th>
                                   <th className="border border-[#cbd5e1] dark:border-zinc-700 bg-[#eff6ff] dark:bg-blue-900/20 p-1 font-bold text-[#dc2626] dark:text-red-500 w-[3.1%]">P</th>
                               </React.Fragment>
                           ))}
                           <th className="border border-[#cbd5e1] dark:border-zinc-700 bg-[#f0fdf4] dark:bg-green-900/20 p-1 font-bold text-[#16a34a] dark:text-green-500 w-[3.1%]">B</th>
                           <th className="border border-[#cbd5e1] dark:border-zinc-700 bg-[#f0fdf4] dark:bg-green-900/20 p-1 font-bold text-[#ca8a04] dark:text-yellow-500 w-[3.1%]">B/B</th>
                           <th className="border border-[#cbd5e1] dark:border-zinc-700 bg-[#f0fdf4] dark:bg-green-900/20 p-1 font-bold text-[#dc2626] dark:text-red-500 w-[3.1%]">P</th>
                       </tr>
                   </thead>
                   <tbody className="bg-white dark:bg-zinc-950">
                       {processedTable.map((route, idx) => (
                               <tr key={idx} className="hover:bg-gray-50 dark:hover:bg-zinc-900 transition-colors">
                                   <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 text-left bg-[#f8fafc] dark:bg-zinc-900/50 text-[#000000] dark:text-gray-200 truncate">
                                       {route.fullName}
                                   </td>
                                   {weekDates.map(date => {
                                       const d = route.days[date];
                                       const dayOfWeek = new Date(date).getDay();
                                       const isWeekendEmpty = (dayOfWeek === 6 || dayOfWeek === 0) && !processedTable.some(r => r.days[date]);

                                       // 💡 මුළු දවසටම දත්ත නැති සෙනසුරාදා / ඉරිදා සඳහා එකවර rowSpan එකක් මඟින් තනි වරක් පෙන්වීම
                                       if (isWeekendEmpty) {
                                           if (idx === 0) {
                                               return (
                                                   <td 
                                                       key={date} 
                                                       rowSpan={processedTable.length} 
                                                       colSpan={3} 
                                                       className="border border-[#cbd5e1] dark:border-zinc-700 p-2 text-center font-bold text-[#6b7280] dark:text-gray-500 bg-[#f8fafc] dark:bg-zinc-900/30 text-[13px] tracking-widest align-middle"
                                                   >
                                                       {dayOfWeek === 6 ? t.saturday : t.holiday}
                                                   </td>
                                               );
                                           }
                                           return null; // පළමු පේළිය හැර අනෙක් පේළි වලදී මෙම cell එක skip කරයි
                                       }

                                       // සාමාන්‍ය දිනවල දත්ත නොමැති විට "-" පෙන්වීම
                                       if (!d) {
                                           return (
                                               <React.Fragment key={date}>
                                                   <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold text-[#9ca3af] dark:text-zinc-600">-</td>
                                                   <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold text-[#9ca3af] dark:text-zinc-600">-</td>
                                                   <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold text-[#9ca3af] dark:text-zinc-600">-</td>
                                               </React.Fragment>
                                           );
                                       }
                                       
                                       const styleB = d.b < 55 ? "bg-[#fee2e2] dark:bg-red-900/20 text-[#dc2626] dark:text-red-500" : "text-[#1f2937] dark:text-gray-300";
                                       const styleBB = d.bb > 5 ? "bg-[#dcfce7] dark:bg-green-900/20 text-[#16a34a] dark:text-green-500" : "text-[#1f2937] dark:text-gray-300";
                                       const styleP = d.p > 45 ? "bg-[#fef08a] dark:bg-yellow-900/20 text-[#ca8a04] dark:text-yellow-500" : "text-[#1f2937] dark:text-gray-300";

                                       return (
                                           <React.Fragment key={date}>
                                               <td className={`border border-[#cbd5e1] dark:border-zinc-700 p-1.5  ${d.b ? styleB : 'text-[#9ca3af] dark:text-zinc-600'}`}>{d.b || "-"}</td>
                                               <td className={`border border-[#cbd5e1] dark:border-zinc-700 p-1.5  ${d.bb ? styleBB : 'text-[#9ca3af] dark:text-zinc-600'}`}>{d.bb || "-"}</td>
                                               <td className={`border border-[#cbd5e1] dark:border-zinc-700 p-1.5  ${d.p ? styleP : 'text-[#9ca3af] dark:text-zinc-600'}`}>{d.p || "-"}</td>
                                           </React.Fragment>
                                       );
                                   })}
                                   
                                   {/* Averages */}
                                   <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold text-[#1f2937] dark:text-gray-300">{route.avg.b || "-"}</td>
                                   <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold text-[#1f2937] dark:text-gray-300">{route.avg.bb || "-"}</td>
                                   <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 font-bold text-[#1f2937] dark:text-gray-300">{route.avg.p || "-"}</td>
                                   
                                   {/* Rank */}
                                   <td className="border border-[#cbd5e1] dark:border-zinc-700 border-l-0 p-1.5 font-bold text-[#dc2626] dark:text-red-500 bg-[#ffffff] dark:bg-zinc-950">
                                       {route.rank !== "-" ? route.rank : ""}
                                   </td>
                               </tr>
                       ))}

                        <tr className="bg-[#f0fdf4] dark:bg-green-900/20">
                            <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1.5 text-left font-bold bg-[#D7EEF7] dark:bg-blue-900/30 text-[#374151] dark:text-gray-200 truncate">
                                {t.grandAvgLabel}
                            </td>
                            {Array.from({ length: 21 }).map((_, i) => (
                                <td key={`empty-avg-${i}`} className="border border-[#cbd5e1] dark:border-zinc-700 p-1 bg-[#D7EEF7] dark:bg-blue-900/30"></td>
                            ))}
                            <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1 font-bold text-[#1f2937] dark:text-gray-200 bg-[#D7EEF7] dark:bg-blue-900/30">{grandAverages.b}</td>
                            <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1 font-bold text-[#1f2937] dark:text-gray-200 bg-[#D7EEF7] dark:bg-blue-900/30">{grandAverages.bb}</td>
                            <td className="border border-[#cbd5e1] dark:border-zinc-700 p-1 font-bold text-[#1f2937] dark:text-gray-200 bg-[#D7EEF7] dark:bg-blue-900/30">{grandAverages.p}</td>
                            <td className="border border-[#cbd5e1] dark:border-zinc-700 border-l-0 p-1 bg-[#D7EEF7] dark:bg-blue-900/30"></td>
                        </tr>
                   </tbody>
                </table>

                {/* 💡 RANKING SMALL TABLES (Current & Previous side by side) */}
                <div className="mt-8 flex flex-col md:flex-row gap-50 items-start justify-center w-full">
                    
                    {/* Previous Week Table */}
                    <div className="flex flex-col items-center">
                        <h3 className="sm:text-xs lg:text-sm font-bold mb-3 flex items-center gap-2 text-gray-800 dark:text-gray-200 w-full justify-center">
                            <History size={18} className="text-gray-500 dark:text-gray-400" /> {t.prevRankTableTitle} <span className="font-semibold italic">({prevWeekDates[0]} - {prevWeekDates[6]})</span>
                        </h3>
                        <table className="border-collapse border border-gray-300 dark:border-zinc-700 sm:text-xs lg:text-sm text-center">
                            <thead className="bg-gray-100 dark:bg-zinc-800 text-gray-800 dark:text-gray-200">
                                <tr>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 w-16">{t.rank}</th>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 pl-3 w-32">{t.route}</th>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 w-20 text-green-700 dark:text-green-500">{t.avgBest}</th>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 w-20 text-yellow-600 dark:text-yellow-500">{t.avgBelowBest}</th>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 w-20 text-red-600 dark:text-red-500">{t.avgPoor}</th>
                                </tr>
                            </thead>
                            <tbody className="bg-white dark:bg-zinc-950">
                                {prevRankTableData.map((r, i) => (
                                    <tr key={i} className="hover:bg-gray-50 dark:hover:bg-zinc-900/50 transition-colors">
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-500 dark:text-gray-400">{r.rank}</td>
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-bold text-left pl-3 text-gray-500 dark:text-gray-400">{r.name}</td>
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-bold text-gray-500 dark:text-gray-400">{r.avg.b}</td>
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-bold text-gray-500 dark:text-gray-400">{r.avg.bb}</td>
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-bold text-gray-500 dark:text-gray-400">{r.avg.p}</td>
                                    </tr>
                                ))}
                                {/* 💡 Average Rows 2 */}
                                <tr className="bg-[#eef2ff] dark:bg-blue-900/30">
                                    <td colSpan={2} className="border border-gray-300 dark:border-zinc-700 p-2 font-bold text-gray-600 dark:text-gray-300 text-right pr-4">{t.withestate} (Avg)</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-600 dark:text-gray-300">{avgPrevWithE.b}</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-600 dark:text-gray-300">{avgPrevWithE.bb}</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-600 dark:text-gray-300">{avgPrevWithE.p}</td>
                                </tr>
                                <tr className="bg-[#D7EEF7] dark:bg-blue-800/40">
                                    <td colSpan={2} className="border border-gray-300 dark:border-zinc-700 p-2 font-bold text-gray-800 dark:text-gray-200 text-right pr-4">{t.withoutestate} (Avg)</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-800 dark:text-gray-200">{avgPrevNoE.b}</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-800 dark:text-gray-200">{avgPrevNoE.bb}</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-800 dark:text-gray-200">{avgPrevNoE.p}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    {/* Current Week Table */}
                    <div className="flex flex-col items-center">
                        <h3 className="sm:text-xs lg:text-sm font-bold mb-3 flex items-center gap-2 text-gray-800 dark:text-gray-200 w-full justify-center">
                            <Trophy size={18} className="text-yellow-500" /> {t.rankTableTitle} <span className="font-semibold italic">({weekDates[0]} - {weekDates[6]})</span>
                        </h3>
                        <table className="border-collapse border border-gray-300 dark:border-zinc-700 sm:text-xs lg:text-sm text-center">
                            <thead className="bg-gray-100 dark:bg-zinc-800 text-gray-800 dark:text-gray-200">
                                <tr>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 w-16">{t.rank}</th>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 pl-3 w-32">{t.route}</th>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 w-20 text-green-700 dark:text-green-500">{t.avgBest}</th>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 w-20 text-yellow-600 dark:text-yellow-500">{t.avgBelowBest}</th>
                                    <th className="border border-gray-300 dark:border-zinc-700 p-2 w-20 text-red-600 dark:text-red-500">{t.avgPoor}</th>
                                </tr>
                            </thead>
                            <tbody className="bg-white dark:bg-zinc-950">
                                {rankTableData.map((r, i) => (
                                    <tr key={i} className="hover:bg-gray-50 dark:hover:bg-zinc-900/50 transition-colors">
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-blue-600 dark:text-blue-400">{r.rank}</td>
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-bold text-left pl-3 dark:text-gray-300">{r.name}</td>
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-bold dark:text-gray-300">{r.avg.b}</td>
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-bold dark:text-gray-300">{r.avg.bb}</td>
                                        <td className="border border-gray-300 dark:border-zinc-700 p-2 font-bold dark:text-gray-300">{r.avg.p}</td>
                                    </tr>
                                ))}
                                {/* 💡 Average Rows 2 */}
                                <tr className="bg-[#eef2ff] dark:bg-blue-900/30">
                                    <td colSpan={2} className="border border-gray-300 dark:border-zinc-700 p-2 font-bold text-gray-600 dark:text-gray-300 text-right pr-4">{t.withestate} (Avg)</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-600 dark:text-gray-300">{avgCurrentWithE.b}</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-600 dark:text-gray-300">{avgCurrentWithE.bb}</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-600 dark:text-gray-300">{avgCurrentWithE.p}</td>
                                </tr>
                                <tr className="bg-[#D7EEF7] dark:bg-blue-800/40">
                                    <td colSpan={2} className="border border-gray-300 dark:border-zinc-700 p-2 font-bold text-gray-800 dark:text-gray-200 text-right pr-4">{t.withoutestate} (Avg)</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-800 dark:text-gray-200">{avgCurrentNoE.b}</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-800 dark:text-gray-200">{avgCurrentNoE.bb}</td>
                                    <td className="border border-gray-300 dark:border-zinc-700 p-2 font-black text-gray-800 dark:text-gray-200">{avgCurrentNoE.p}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                </div> 
            </div>
        )}
      </div>

      {/* ========================================================================================= */}
      {/* 💡 HIDDEN PRINT AREA FOR PDF DIRECT DOWNLOAD (NOW 2 PAGES) */}
      {/* ========================================================================================= */}
      <div 
         id="pdf-print-area" 
         ref={printAreaRef}
         style={{ display: 'none' }}
      >
          {/* 📄 PAGE 1: MAIN REPORT */}
          <div id="pdf-page-1" className="bg-[#ffffff] p-8 font-sans text-[#000000] flex flex-col justify-between" style={{ width: '1600px', minHeight: '1130px' }}>
              
              <div>
                  {/* Header */}
                  <div className="flex justify-between items-start mb-6 border-b border-[#d1d5db] pb-4">
                      <div className="flex items-center gap-4">
                          <img src="/logo.png" alt="Logo" className="w-20 h-20 object-contain" onError={(e) => e.target.style.display = 'none'} />
                          <div>
                              <h1 className="text-3xl font-bold text-[#1B6A31] uppercase" style={{ fontFamily: 'sans-serif' }}>
                                  Athukorala Group (Pvt) Ltd
                              </h1>
                              <h2 className="text-2xl font-bold mt-2" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                                  {t.reportTitle}
                              </h2>
                              <p className="text-xl mt-1" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                                  {t.dateRange} 
                                  <span className="font-extrabold text-[#4d7c0f] tracking-wide ml-2">{weekDates[0]}</span> 
                                  <span className="mx-2 font-medium">{t.to}</span> 
                                  <span className="font-extrabold text-[#4d7c0f] tracking-wide">{weekDates[6]}</span>
                              </p>
                          </div>
                      </div>
                      <div className="text-right text-sm text-[#6b7280] flex flex-col gap-1.5" style={{ fontFamily: 'sans-serif' }}>
                          <p><strong className="text-[#4b5563]">{t.docRef}:</strong> {uniqueCode}</p>
                          <p><strong className="text-[#4b5563]">{t.genTime}:</strong> {generatedDateTime}</p>
                      </div>
                  </div>

                  {/* Horizontal Legend */}
                  <div className="border border-[#e5e7eb] rounded-lg p-4 mb-6 flex items-center justify-start gap-16 text-[14px] bg-[#f8fafc]" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                      <div className="flex gap-4 leading-none items-center">
                          <span className="w-5 h-5 bg-[#ffcccc] border border-[#fca5a5] flex-shrink-0 rounded-sm"></span> 
                          <span className="translate-y-[1px] font-bold text-[#4b5563]">{t.legendRed}</span>
                      </div>
                      <div className="flex gap-4 leading-none items-center">
                          <span className="w-5 h-5 bg-[#dcfce7] border border-[#86efac] flex-shrink-0 rounded-sm"></span> 
                          <span className="translate-y-[1px] font-bold text-[#4b5563]">{t.legendGreen}</span>
                      </div>
                      <div className="flex gap-4 leading-none items-center">
                          <span className="w-5 h-5 bg-[#fef08a] border border-[#fde047] flex-shrink-0 rounded-sm"></span> 
                          <span className="translate-y-[1px] font-bold text-[#4b5563]">{t.legendYellow}</span>
                      </div>
                  </div>

                  {/* Main Table (Enlarged) */}
                  <table className="w-full table-fixed border-collapse border border-[#cbd5e1] text-center text-[15px]" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                      <thead>
                          <tr>
                              <th rowSpan={2} className="text-center border border-[#cbd5e1] p-2.5 font-extrabold bg-[#f3f4f6] text-[#000000] w-[15%]">
                                  {t.supplier}
                              </th>
                              {weekDates.map(date => (
                                  <th key={date} colSpan={3} className="border border-[#cbd5e1] p-2.5 font-extrabold bg-[#eff6ff] text-[#000000]">
                                      {date.split('-').slice(1).join('/')}
                                  </th>
                              ))}
                              <th colSpan={3} className="border border-[#cbd5e1] p-2.5 font-extrabold bg-[#f0fdf4] text-[#000000] whitespace-nowrap">
                                  {t.weeklyAvg}
                              </th>
                              <th rowSpan={2} className="border border-[#cbd5e1] p-2.5 font-extrabold bg-[#f3f4f6] text-[#dc2626] w-[6%]">
                                  {t.rank}
                              </th>
                          </tr>
                          <tr>
                              {weekDates.map((_, i) => (
                                  <React.Fragment key={i}>
                                      <th className="border border-[#cbd5e1] bg-[#eff6ff] p-1.5 font-bold text-[#16a34a] w-[3.1%]">B</th>
                                      <th className="border border-[#cbd5e1] bg-[#eff6ff] p-1.5 font-bold text-[#ca8a04] w-[3.1%]">B/B</th>
                                      <th className="border border-[#cbd5e1] bg-[#eff6ff] p-1.5 font-bold text-[#dc2626] w-[3.1%]">P</th>
                                  </React.Fragment>
                              ))}
                              <th className="border border-[#cbd5e1] bg-[#f0fdf4] p-1.5 font-bold text-[#16a34a] w-[3.1%]">B</th>
                              <th className="border border-[#cbd5e1] bg-[#f0fdf4] p-1.5 font-bold text-[#ca8a04] w-[3.1%]">B/B</th>
                              <th className="border border-[#cbd5e1] bg-[#f0fdf4] p-1.5 font-bold text-[#dc2626] w-[3.1%]">P</th>
                          </tr>
                      </thead>
                      <tbody className="text-center">
                          {processedTable.map((route, idx) => (
                              <tr key={idx}>
                                  <td className="border border-[#cbd5e1] p-2 text-left bg-[#f8fafc] text-[#000000] truncate">
                                      {route.fullName}
                                  </td>
                                  {weekDates.map(date => {
                                      const d = route.days[date];
                                      const dayOfWeek = new Date(date).getDay();
                                      const isWeekendEmpty = (dayOfWeek === 6 || dayOfWeek === 0) && !processedTable.some(r => r.days[date]);

                                      if (isWeekendEmpty) {
                                          if (idx === 0) {
                                              return (
                                                  <td key={date} rowSpan={processedTable.length} colSpan={3} className="border border-[#cbd5e1] p-2 text-center text-[#000000] bg-[#f8fafc] text-[16px] tracking-widest align-middle">
                                                      {dayOfWeek === 6 ? t.saturday : t.holiday}
                                                  </td>
                                              );
                                          }
                                          return null;
                                      }

                                      if (!d) {
                                          return (
                                              <React.Fragment key={date}>
                                                  <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                                  <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                                  <td className="border border-[#cbd5e1] p-1.5 font-bold text-[#9ca3af]">-</td>
                                              </React.Fragment>
                                          );
                                      }

                                      const styleB = d.b < 55 ? "bg-[#fee2e2] text-[#000000] " : "text-[#000000] ";
                                      const styleBB = d.bb > 5 ? "bg-[#dcfce7] text-[#000000] " : "text-[#000000] ";
                                      const styleP = d.p > 45 ? "bg-[#fef08a] text-[#000000] " : "text-[#000000] ";

                                      return (
                                          <React.Fragment key={date}>
                                              <td className={`border border-[#cbd5e1] p-1.5 ${d.b ? styleB : 'text-[#000000]'}`}>{d.b || "-"}</td>
                                              <td className={`border border-[#cbd5e1] p-1.5 ${d.bb ? styleBB : 'text-[#000000]'}`}>{d.bb || "-"}</td>
                                              <td className={`border border-[#cbd5e1] p-1.5 ${d.p ? styleP : 'text-[#000000]'}`}>{d.p || "-"}</td>
                                          </React.Fragment>
                                      );
                                  })}
                                  
                                  <td className="border border-[#cbd5e1] p-1.5 font-black text-[#1f2937]">{route.avg.b || "-"}</td>
                                  <td className="border border-[#cbd5e1] p-1.5 font-black text-[#1f2937]">{route.avg.bb || "-"}</td>
                                  <td className="border border-[#cbd5e1] p-1.5 font-black text-[#1f2937]">{route.avg.p || "-"}</td>
                                  
                                  <td className="border border-[#cbd5e1] border-l-0 p-1.5 font-black text-[#dc2626] text-[15px] bg-[#ffffff]">
                                      {route.rank !== "-" ? route.rank : ""}
                                  </td>
                              </tr>
                          ))}

                          <tr>
                              <td className="border border-[#cbd5e1] p-2 text-left font-bold bg-[#f0fdf4]">
                                  {t.grandAvgLabel}
                              </td>
                              {Array.from({ length: 21 }).map((_, i) => (
                                  <td key={`pdf-empty-avg-${i}`} className="border border-[#cbd5e1] p-1.5 bg-[#f0fdf4]"></td>
                              ))}
                              <td className="border border-[#cbd5e1] p-1.5 font-black bg-[#f0fdf4]">{grandAverages.b}</td>
                              <td className="border border-[#cbd5e1] p-1.5 font-black bg-[#f0fdf4]">{grandAverages.bb}</td>
                              <td className="border border-[#cbd5e1] p-1.5 font-black bg-[#f0fdf4]">{grandAverages.p}</td>
                              <td className="border border-[#cbd5e1] border-l-0 p-1.5 bg-[#f0fdf4]"></td>
                          </tr>

                          {/* EXTRA ROWS */}
                          {[t.participation, t.qualityOfficer, t.teaInspector, t.deputyCommissioner, t.registeredProducer].map((label, idx) => (
                              <tr key={`pdf-extra-${idx}`}>
                                  <td className="border border-[#cbd5e1] p-2 text-left font-bold bg-[#f8fafc] text-[#374151] truncate">{label}</td>
                                  {Array.from({ length: 25 }).map((_, i) => (
                                      <td key={i} className="border border-[#cbd5e1] p-1.5"></td>
                                  ))}
                              </tr>
                          ))}
                      </tbody>
                  </table>
              </div>
              
              {/* Bottom Text Page 1 */}
              <div className="text-center font-bold mt-2 text-[14px] text-[#000000]" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                  {t.footerText}
              </div>

              {/* FOOTER SIGNATURES Page 1 */}
              <div className="mt-auto pt-16 pb-12 w-full flex flex-row justify-between px-16 items-end text-[16px] font-bold font-sans text-[#374151]">                  
                  <div className="text-center">
                      <p className="text-[#4b5563] font-sans mb-2">{t.signGen}</p>
                      <p className="text-[#2C3A3A] font-sans">{currentUsername} ({userRole})</p>
                  </div>
                  <div className="text-center">
                      <p className="text-[#4b5563] mb-2">.............................................................</p>
                      <p className="text-[#4b5563]">{t.signFac}</p>
                  </div>
                  <div className="text-center">
                      <p className="text-[#4b5563] mb-2">.............................................................</p>
                      <p className="text-[#4b5563]">{t.signChair}</p>
                  </div>
              </div>
          </div>

          {/* 📄 PAGE 2: RANKING & SIGNATURES */}
          <div id="pdf-page-2" className="bg-[#ffffff] p-8 font-sans text-[#000000] flex flex-col justify-between" style={{ width: '1600px', minHeight: '1130px' }}>
              
              {/* Header (Repeated for Context) */}
              <div className="flex justify-between items-start mb-10 border-b border-[#d1d5db] pb-4">
                  <div className="flex items-center gap-4">
                      <img src="/logo.png" alt="Logo" className="w-20 h-20 object-contain" onError={(e) => e.target.style.display = 'none'} />
                      <div>
                          <h1 className="text-3xl font-bold text-[#1B6A31] uppercase" style={{ fontFamily: 'sans-serif' }}>
                              Athukorala Group (Pvt) Ltd
                          </h1>
                          <h2 className="text-2xl font-bold mt-2" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                              {t.reportTitle} - {t.rankTableTitle}
                          </h2>
                      </div>
                  </div>
              </div>

              {/* Ranking Tables side by side (Enlarged) */}
              <div className="flex flex-row justify-center items-start w-full gap-24 flex-grow mt-8">
                  
                  {/* Previous Week Table */}
                  <div className="w-[40%] flex-shrink-0">
                      <h3 className="text-[18px] font-bold mb-4 text-center text-[#4b5563]" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>{t.prevRankTableTitle} <span className="font-semibold italic">({prevWeekDates[0]} - {prevWeekDates[6]})</span></h3>
                      <table className="w-full border-collapse border border-[#cbd5e1] text-center text-[16px]" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                          <thead className="bg-[#e5e7eb] ">
                              <tr>
                                  <th className="border border-[#cbd5e1] p-3  text-[#4b5563]">{t.rank}</th>
                                  <th className="border border-[#cbd5e1] p-3 text-[#4b5563]">{t.route}</th>
                                  <th className="border border-[#cbd5e1] p-3 text-[#4b5563]">{t.avgBest}</th>
                                  <th className="border border-[#cbd5e1] p-3 text-[#4b5563]">{t.avgBelowBest}</th>
                                  <th className="border border-[#cbd5e1] p-3 text-[#4b5563]">{t.avgPoor}</th>
                              </tr>
                          </thead>
                          <tbody className="text-center">
                              {prevRankTableData.map((r, i) => (
                                  <tr key={i}>
                                      <td className="border border-[#cbd5e1] p-3 font-black text-[#4b5563]">{r.rank}</td>
                                      <td className="border border-[#cbd5e1] p-3 font-bold text-[#4b5563]">{r.name}</td>
                                      <td className="border border-[#cbd5e1] p-3 font-bold text-[#4b5563]">{r.avg.b}</td>
                                      <td className="border border-[#cbd5e1] p-3 font-bold text-[#4b5563]">{r.avg.bb}</td>
                                      <td className="border border-[#cbd5e1] p-3 font-bold text-[#4b5563]">{r.avg.p}</td>
                                  </tr>
                              ))}
                              {/* Average Rows 2 */}
                              <tr className="bg-[#f1f5f9]">
                                  <td colSpan={2} className="border border-[#cbd5e1] p-3 font-bold text-[#4b5563] text-right pr-6">{t.withestate} (Avg)</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#4b5563]">{avgPrevWithE.b}</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#4b5563]">{avgPrevWithE.bb}</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#4b5563]">{avgPrevWithE.p}</td>
                              </tr>
                              <tr className="bg-[#D7EEF7]">
                                  <td colSpan={2} className="border border-[#cbd5e1] p-3 font-bold text-[#000000] text-right pr-6">{t.withoutestate} (Avg)</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#000000]">{avgPrevNoE.b}</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#000000]">{avgPrevNoE.bb}</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#000000]">{avgPrevNoE.p}</td>
                              </tr>
                          </tbody>
                      </table>
                  </div>

                  {/* Current Week Table */}
                  <div className="w-[40%] flex-shrink-0">
                      <h3 className="text-[18px] font-bold mb-4 text-center text-[#000000]" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>{t.rankTableTitle}  <span className="font-semibold italic">({weekDates[0]} - {weekDates[6]})</span></h3>
                      <table className="w-full border-collapse border border-[#cbd5e1] text-center text-[16px]" style={{ fontFamily: 'Iskoola Pota, sans-serif' }}>
                          <thead className="bg-[#e5e7eb]">
                              <tr>
                                  <th className="border border-[#cbd5e1] p-3">{t.rank}</th>
                                  <th className="border border-[#cbd5e1] p-3">{t.route}</th>
                                  <th className="border border-[#cbd5e1] p-3 text-[#087034]">{t.avgBest}</th>
                                  <th className="border border-[#cbd5e1] p-3 text-[#CE950E]">{t.avgBelowBest}</th>
                                  <th className="border border-[#cbd5e1] p-3 text-[#DE2E17]">{t.avgPoor}</th>
                              </tr>
                          </thead>
                          <tbody className="text-center">
                              {rankTableData.map((r, i) => (
                                  <tr key={i}>
                                      <td className="border border-[#cbd5e1] p-3 font-bold text-[#1d4ed8]">{r.rank}</td>
                                      <td className="border border-[#cbd5e1] p-3 font-bold">{r.name}</td>
                                      <td className="border border-[#cbd5e1] p-3 font-bold">{r.avg.b}</td>
                                      <td className="border border-[#cbd5e1] p-3 font-bold">{r.avg.bb}</td>
                                      <td className="border border-[#cbd5e1] p-3 font-bold">{r.avg.p}</td>
                                  </tr>
                              ))}
                              {/* Average Rows 2 */}
                              <tr className="bg-[#f1f5f9]">
                                  <td colSpan={2} className="border border-[#cbd5e1] p-3 font-bold text-[#4b5563] text-right pr-6">{t.withestate} (Avg)</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#4b5563]">{avgCurrentWithE.b}</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#4b5563]">{avgCurrentWithE.bb}</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#4b5563]">{avgCurrentWithE.p}</td>
                              </tr>
                              <tr className="bg-[#D7EEF7]">
                                  <td colSpan={2} className="border border-[#cbd5e1] p-3 font-bold text-[#000000] text-right pr-6">{t.withoutestate} (Avg)</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#000000]">{avgCurrentNoE.b}</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#000000]">{avgCurrentNoE.bb}</td>
                                  <td className="border border-[#cbd5e1] p-3 font-black text-[#000000]">{avgCurrentNoE.p}</td>
                              </tr>
                          </tbody>
                      </table>
                  </div>

              </div>

              {/* FOOTER SIGNATURES Page 2 */}
              <div className="mt-auto pt-16 pb-12 w-full flex flex-row justify-between px-16 items-end text-[16px] font-bold font-sans text-[#374151]">                  
                  <div className="text-center">
                      <p className="text-[#4b5563] font-sans mb-2">{t.signGen}</p>
                      <p className="text-[#2C3A3A] font-sans">{currentUsername} ({userRole})</p>
                  </div>
                  <div className="text-center">
                      <p className="text-[#4b5563] mb-2">.............................................................</p>
                      <p className="text-[#4b5563]">{t.signFac}</p>
                  </div>
                  <div className="text-center">
                      <p className="text-[#4b5563] mb-2">.............................................................</p>
                      <p className="text-[#4b5563]">{t.signChair}</p>
                  </div>
              </div>

          </div>
      </div>
    </div>
  );
}